markdown: kramdown
baseurl: Hashes_2.0
exclude: ['README.md, JEKYLL.md']
permalink: pretty
timezone: Kolkata/Asia
sass:
    sass_dir: assets/css
    style: compressed
plugins:
    - jekyll-minifier
    - jekyll-last-modified-at
google_analytics:
  id: ""
